### ISSUE TITLE
Add leading zero on single-digit numbers

### ISSUE THREAD

**Issue by calendaric** [calendaric/calic#3]
Please add a leading zero in front of single digits so that they look natural and familiar, like this:
```
29 30 31 01 02 03 04
05 06 07 08 09 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30 31 01
02 03 04 05 06 07 08
```

**Comment by froly** [comment]
I think that leading zeroes is the most unnatural and unfamiliar thing in calendars. Just check out mac os calendar (and google and so on)

<img width="155" alt="image" src="https://user-images.githubusercontent.com/7168807/62827161-c25e5880-bbd2-11e9-8f3b-a8e2e49d086f.png">
